import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawn } from 'node:child_process';
import { inflateRawSync } from 'node:zlib';

const repoRoot=path.resolve(import.meta.dirname,'..'); const artifactRoot=path.join(repoRoot,'artifacts'); const evidenceRoot=path.join(repoRoot,'verification','evidence'); const sqlite=process.env.SQLITE3_PATH||'sqlite3.exe'; const attachments=['输入数据包.zip','reference.zip','关键标准答案.xlsx','任务规格转化.xlsx'];
const expectedReference=['output/affiliate_payout_repaired.db','output/reports/commission_ledger.csv','output/reports/excluded_touchpoints.csv','output/reports/partner_summary.csv','output/sql/rebuild_affiliate_payout.sql'].sort(); const sourceTables=['orders','click_touchpoints','partner_accounts','refunds']; const derivedTables=['commission_ledger','excluded_touchpoints','partner_summary'];
const assert=(value,message)=>{if(!value)throw new Error(message);}; const sha256=(bytes)=>crypto.createHash('sha256').update(bytes).digest('hex'); const sha256File=(file)=>sha256(fs.readFileSync(file));
function zipEntries(file){const data=fs.readFileSync(file);let eocd=-1;for(let index=data.length-22;index>=Math.max(0,data.length-65557);index--){if(data.readUInt32LE(index)===0x06054b50){eocd=index;break;}}assert(eocd>=0,`找不到ZIP目录：${file}`);const count=data.readUInt16LE(eocd+10);let offset=data.readUInt32LE(eocd+16);const entries=new Map();for(let i=0;i<count;i++){assert(data.readUInt32LE(offset)===0x02014b50,`ZIP目录损坏：${file}`);const method=data.readUInt16LE(offset+10),compressedSize=data.readUInt32LE(offset+20),uncompressedSize=data.readUInt32LE(offset+24),nameLength=data.readUInt16LE(offset+28),extraLength=data.readUInt16LE(offset+30),commentLength=data.readUInt16LE(offset+32),localOffset=data.readUInt32LE(offset+42),name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/'),localNameLength=data.readUInt16LE(localOffset+26),localExtraLength=data.readUInt16LE(localOffset+28),start=localOffset+30+localNameLength+localExtraLength;if(!name.endsWith('/')){const compressed=data.subarray(start,start+compressedSize);const body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===uncompressedSize,`无法解压${name}`);entries.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return entries;}
async function extract(file,destination){for(const [name,bytes] of zipEntries(file)){const target=path.resolve(destination,...name.split('/'));assert(target.startsWith(`${path.resolve(destination)}${path.sep}`),`非法ZIP路径：${name}`);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function workbookSheets(file){const xml=zipEntries(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map((m)=>m[1]);}
async function run(command,args,cwd){const started=Date.now();return await new Promise((resolve)=>{let child;try{child=spawn(command,args,{cwd,env:process.env,windowsHide:true});}catch(error){resolve({code:1,stdout:'',stderr:error.stack??error.message,elapsed_ms:Date.now()-started});return;}let stdout='',stderr='',settled=false;child.stdout.on('data',(c)=>{stdout+=c;});child.stderr.on('data',(c)=>{stderr+=c;});child.on('error',(e)=>{if(!settled){settled=true;resolve({code:1,stdout,stderr:`${stderr}${e.stack??e.message}`,elapsed_ms:Date.now()-started});}});child.on('exit',(code)=>{if(!settled){settled=true;resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});}});});}
async function query(database,sql){const result=await run(sqlite,['-batch','-readonly','-json',database,sql],repoRoot);assert(result.code===0,`SQLite查询失败\n${result.stderr||result.stdout}`);return JSON.parse(result.stdout||'[]');}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/u,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/u,''));rows.push(row);}const headers=rows.shift()??[];return rows.filter((values)=>values.some((v)=>v!=='')).map((values)=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])));}
function files(root){const out=[];function walk(current,prefix=''){if(!fs.existsSync(current))return;for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())walk(path.join(current,entry.name),relative);else out.push(relative);}}walk(root);return out.sort();}
function treeDigest(root,ignored=new Set()){const lines=[];function walk(current,prefix=''){for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(ignored.has(relative.split('/')[0]))continue;const full=path.join(current,entry.name);if(entry.isDirectory())walk(full,relative);else lines.push(`${relative}\0${sha256File(full)}`);}}walk(root);return sha256(Buffer.from(lines.join('\n')));}
function classify(name,bytes){const lower=name.toLowerCase();if(bytes.length>=4&&bytes[0]===0x7f&&bytes.subarray(1,4).toString('ascii')==='ELF')return'linux_elf';if(/\.(?:sh|bash|so)(?:\.|$)/u.test(lower))return'posix_member';if(/^#!.*(?:ba|z|k)?sh/mu.test(bytes.subarray(0,160).toString('utf8')))return'posix_shebang';return null;}
async function prepare(label,mutate){const root=path.join(os.tmpdir(),label);await fsp.rm(root,{recursive:true,force:true});await fsp.mkdir(root,{recursive:true});await extract(path.join(artifactRoot,'输入数据包.zip'),root);const inputRoot=path.join(root,'input_data');const reference=zipEntries(path.join(artifactRoot,'reference.zip'));const outputRoot=path.join(root,'output');await fsp.mkdir(path.join(inputRoot,'starter'),{recursive:true});await fsp.writeFile(path.join(inputRoot,'starter','rebuild_affiliate_payout.sql'),reference.get('output/sql/rebuild_affiliate_payout.sql'));if(mutate)await mutate(inputRoot);return{root,inputRoot,outputRoot,reference};}
async function execute(inputRoot){return await run('python',['tools/run_task.py'],inputRoot);}
function stableRows(rows,keys){return rows.toSorted((a,b)=>keys.map((key)=>String(a[key]).localeCompare(String(b[key]),'en')).find((value)=>value!==0)??0);}
async function compareReference(outputRoot,reference){const actual=files(outputRoot).map((name)=>`output/${name}`);assert(JSON.stringify(actual)===JSON.stringify(expectedReference),`输出成员错误：${actual.join(',')}`);const semantic=crypto.createHash('sha256');const sqlActual=fs.readFileSync(path.join(outputRoot,'sql','rebuild_affiliate_payout.sql'),'utf8').replaceAll('\r\n','\n');const sqlExpected=reference.get('output/sql/rebuild_affiliate_payout.sql').toString('utf8').replaceAll('\r\n','\n');assert(sqlActual===sqlExpected,'完成版SQL与Reference不一致');semantic.update(sqlActual);
  for(const [file,keys] of [['commission_ledger.csv',['order_id']],['excluded_touchpoints.csv',['order_id','click_id']],['partner_summary.csv',['partner_id']]]){const actualRows=stableRows(parseCsv(fs.readFileSync(path.join(outputRoot,'reports',file),'utf8')),keys);const expectedRows=stableRows(parseCsv(reference.get(`output/reports/${file}`).toString('utf8')),keys);assert(JSON.stringify(actualRows)===JSON.stringify(expectedRows),`${file}业务字段与Reference不一致`);semantic.update(JSON.stringify(actualRows));}
  const refDb=path.join(outputRoot,'.reference.db');await fsp.writeFile(refDb,reference.get('output/affiliate_payout_repaired.db'));try{for(const table of [...sourceTables,...derivedTables]){const schemaA=await query(path.join(outputRoot,'affiliate_payout_repaired.db'),`PRAGMA table_info(${table});`);const schemaB=await query(refDb,`PRAGMA table_info(${table});`);assert(JSON.stringify(schemaA)===JSON.stringify(schemaB),`${table}结构与Reference不一致`);const rowsA=(await query(path.join(outputRoot,'affiliate_payout_repaired.db'),`SELECT * FROM ${table};`)).toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b),'en'));const rowsB=(await query(refDb,`SELECT * FROM ${table};`)).toSorted((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b),'en'));assert(JSON.stringify(rowsA)===JSON.stringify(rowsB),`${table}数据与Reference不一致`);semantic.update(JSON.stringify(rowsA));}const integrity=await query(path.join(outputRoot,'affiliate_payout_repaired.db'),'PRAGMA integrity_check;');assert(Object.values(integrity[0]??{})[0]==='ok','数据库完整性检查失败');}finally{await fsp.rm(refDb,{force:true});}return semantic.digest('hex');}

await fsp.rm(evidenceRoot,{recursive:true,force:true});await fsp.mkdir(evidenceRoot,{recursive:true});assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','只接受GitHub托管Windows运行');const sqliteVersion=await run(sqlite,['--version'],repoRoot);assert(sqliteVersion.code===0&&sqliteVersion.stdout.startsWith('3.51.2'),`需要SQLite3.51.2，当前为${sqliteVersion.stdout||sqliteVersion.stderr}`);const pythonVersion=await run('python',['--version'],repoRoot);assert(pythonVersion.code===0&&/Python 3\.12/u.test(`${pythonVersion.stdout}${pythonVersion.stderr}`),'需要Python3.12');
const attachmentSha256=Object.fromEntries(attachments.map((name)=>[name,sha256File(path.join(artifactRoot,name))]));const inputMembers=zipEntries(path.join(artifactRoot,'输入数据包.zip'));const executableScan=[...inputMembers].map(([name,bytes])=>({name,classification:classify(name,bytes)})).filter((item)=>item.classification);assert(executableScan.length===0,`输入包含平台专用成员：${JSON.stringify(executableScan)}`);assert(JSON.stringify([...zipEntries(path.join(artifactRoot,'reference.zip')).keys()].sort())===JSON.stringify(expectedReference),'Reference成员错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'关键标准答案Sheet错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'任务规格Sheet错误');const solution=zipEntries(path.join(artifactRoot,'reference.zip')).get('output/sql/rebuild_affiliate_payout.sql').toString('utf8');assert(!/\b(?:O-\d+|C-\d+|P-[A-Z])\b/u.test(solution),'完成版SQL含样例主键硬编码');
const cleanRuns=[];for(const label of ['Q10423 第一次 中文 空目录','Q10423 第二次 中文 空格目录']){const room=await prepare(label);const before=treeDigest(room.inputRoot);const result=await execute(room.inputRoot);assert(result.code===0,`${label}业务入口失败\n${result.stdout}\n${result.stderr}`);const after=treeDigest(room.inputRoot);assert(before===after,`${label}修改了输入`);const semantic=await compareReference(room.outputRoot,room.reference);cleanRuns.push({directory_label:label,process_runs:1,exit_codes:[result.code],input_digest_before:before,input_digest_after:after,semantic_digest:semantic,elapsed_ms:[result.elapsed_ms],reference_match:true});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'两个目录的结构化结果不一致');
const crlf=await prepare('Q10423 CRLF 规则合同',async(inputRoot)=>{const file=path.join(inputRoot,'rules','commission_rules.json');const value=await fsp.readFile(file,'utf8');await fsp.writeFile(file,value.replace(/\r?\n/gu,'\r\n'));});let result=await execute(crlf.inputRoot);assert(result.code===0,`CRLF规则合同失败\n${result.stdout}\n${result.stderr}`);const crlfDigest=await compareReference(crlf.outputRoot,crlf.reference);assert(crlfDigest===cleanRuns[0].semantic_digest,'CRLF改变业务结果');
const mutation=await prepare('Q10423 佣金档位变化',async(inputRoot)=>{const file=path.join(inputRoot,'rules','commission_rules.json');const value=JSON.parse(await fsp.readFile(file,'utf8'));value.commission_rate_bps_by_tier.preferred=750;await fsp.writeFile(file,`${JSON.stringify(value,null,2)}\n`);});result=await execute(mutation.inputRoot);assert(result.code===0,`佣金档位变化失败\n${result.stdout}\n${result.stderr}`);const ledger=parseCsv(await fsp.readFile(path.join(mutation.outputRoot,'reports','commission_ledger.csv'),'utf8'));const baseline=parseCsv(zipEntries(path.join(artifactRoot,'reference.zip')).get('output/reports/commission_ledger.csv').toString('utf8'));const changed=ledger.filter((row)=>baseline.find((base)=>base.order_id===row.order_id)?.commission_cents!==row.commission_cents);assert(changed.length>0&&changed.every((row)=>row.commission_rate_bps==='750'),'有效规则变化未联动佣金');assert(ledger.every((row)=>baseline.find((base)=>base.order_id===row.order_id)?.attributed_click_id===row.attributed_click_id),'佣金率变化不应改变归因身份');
const negative=await prepare('Q10423 缺失结算规则',async(inputRoot)=>{await fsp.rm(path.join(inputRoot,'rules','commission_rules.json'));});result=await execute(negative.inputRoot);const derivedAbsent=!fs.existsSync(negative.outputRoot);assert(result.code!==0&&derivedAbsent,'结算规则缺失时没有非零退出或仍有交付物');
const evidence={schema_version:1,task_asset_id:'sqlite_affiliate_payout_settlement',result:'PASS',generated_at_utc:new Date().toISOString(),git_commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,runner:{os:process.env.RUNNER_OS,arch:process.env.RUNNER_ARCH,image_os:process.env.ImageOS,image_version:process.env.ImageVersion,node:process.version,actual_windows_run:true},software:{sqlite:sqliteVersion.stdout.trim(),python:`${pythonVersion.stdout}${pythonVersion.stderr}`.trim()},attachment_sha256:attachmentSha256,archive_checks:{input_members:[...inputMembers.keys()].sort(),reference_members:expectedReference,prohibited_platform_members:executableScan},workbook_checks:{answer_sheet_names:workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')),specification_sheet_names:workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx'))},clean_runs:cleanRuns,crlf_case:{changed_input:'rules/commission_rules.json行尾改为CRLF',exit_code:0,semantic_digest:crlfDigest,reference_match:true},positive_mutation:{changed_rule:'preferred佣金率从800基点改为750基点',exit_code:0,changed_order_count:changed.length,attribution_identity_unchanged:true},invalid_input:{removed_input:'rules/commission_rules.json',exit_code:result.code,derived_outputs_absent:derivedAbsent},network:{installation_network_access:'仅软件下载安装阶段',formal_run_network_access:'none'}};await fsp.writeFile(path.join(evidenceRoot,'windows-verification.json'),`${JSON.stringify(evidence,null,2)}\n`);const audit={schema_version:1,task_asset_id:evidence.task_asset_id,result:'PASS',platform:process.platform,architecture:process.arch,node_version:process.version,sqlite_version:sqliteVersion.stdout.trim(),python_version:`${pythonVersion.stdout}${pythonVersion.stderr}`.trim(),attachment_sha256:attachmentSha256,input_members:evidence.archive_checks.input_members,reference_members:evidence.archive_checks.reference_members,forbidden_platform_members:executableScan,clean_directory_count:cleanRuns.length,process_runs_per_directory:1};await fsp.writeFile(path.join(evidenceRoot,'windows-audit.json'),`${JSON.stringify(audit,null,2)}\n`);console.log(JSON.stringify(evidence,null,2));
